name: ✨ Feature Request
description: Suggest a new feature for ChocoDrop
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We love hearing new ideas.

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - AI Model Integration
        - 3D Framework Support
        - User Interface
        - Natural Language Processing
        - Documentation
        - API Enhancement
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "As a developer, I want to..."

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered other solutions?

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would you use this feature in your project?

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I'd like to work on this feature
        - label: I can provide testing/feedback
        - label: I can help with documentation