name: CI

on:
  push:
    branches: ['**']  # すべてのブランチで実行
  pull_request:
    branches: ['**']  # すべてのブランチへの PR で実行

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build --if-present

      - name: Run tests (daemon)
        run: |
          cd packages/daemon
          npm test

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
        continue-on-error: true
        # TODO: 既存コードの lint エラーを修正後、continue-on-error を削除

      - name: Check formatting with Prettier
        run: npm run format:check
        continue-on-error: true
        # TODO: 既存コードのフォーマットを修正後、continue-on-error を削除
